name: Deploy to GitHub Pages from Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install
          npm run build # This builds the project (Vite in this case)

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main  # You're deploying directly to the `main` branch
          FOLDER: dist  # This should be the folder, not a specific file (e.g., dist, not /dist/index.html)
