name: Deploy to GitHub Pages from Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build (optional)
        run: |
          npm install
          npm run build # Use this if you're building a static site with a tool like React or Vite

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main 
          FOLDER: Authentication-Client